version: "3.7"

services:
  app:
    restart: always
    image: center-mall:latest
    network_mode: "host"
    volumes:
      - kafka_state_dir:/var/lib/kafka-streams-state
      - logging_dir:/var/log/nextgen

volumes:
  kafka_state_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/lib/kafka-streams-state
  logging_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/log/nextgen
